### ISSUE TITLE
getMembers returns only first 10 members of list

### ISSUE THREAD

**Issue by lessrand** [alexanderwe/bananaj#1]
Hello,

using the following code, getMembers only returns the first 10 Members (the list has 1500)

kind regards

Randolph

	public static void main(String[] args)
	{
		try
		{
			MailchimpConnection con = new MailchimpConnection("xxxxxxxx");
			// Get a single list
			MailChimpList myMailchimpList = con.getList("xxxxxxxxxx");
			ArrayList<Member> membersOfList = myMailchimpList.getMembers();
			int count = myMailchimpList.getMembercount();
			System.err.println("List " + myMailchimpList.getName() + " has " + count + " members. I got " + membersOfList.size() + " elements.");

			for(int i = 0; i < membersOfList.size(); i++)
			{
				/* You can also get a specific member by specifying it's id */
				Member memberOfList = membersOfList.get(i);
				String email = memberOfList.getEmail_address();
				MemberStatus status = memberOfList.getStatus();
				System.err.println(status.getStringRepresentation() + ":" + email);
			}
		}
		catch(Exception e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

**Comment by alexanderwe** [comment]
Fixed in https://github.com/alexanderwe/bananaj/commit/f83f9b26f002812cb0347b7f916bf29e8aa6f6b0

You can now specify a count of how many members you want the list to fetch.

`ArrayList<Member> membersOfList = yourList.getMembers(0); // Get all members     ArrayList<Member> partOfMembers = yourList.getMembers(5); // Get first 5 members`

**Comment by lessrand** [comment]
Hello

Works great!
Thanks for the fast update!

kind regards

Randolph

**Comment by alexanderwe** [comment]
No problem !
