### ISSUE TITLE
HttpsURLConnection does not support PATCH requests

### ISSUE THREAD

**Issue by gscriver** [alexanderwe/bananaj#10]
Due to HttpsURLConnection not supporting PATCH requests most Mailchimp update actions can’t be performed. Note that the Mailchimp server does not support the X-HTTP-Method-Override header so that workaround is not viable.

**Comment by alexanderwe** [comment]
Definitely need to check into that, thanks for reporting

**Comment by gscriver** [comment]
Would you be opposed to trying out Apache [HttpClient](https://hc.apache.org/index.html)? This library supports PATCH requests.

**Comment by alexanderwe** [comment]
That’s one option for sure. I also want to take a look st [Unirest](http://unirest.io/java.html) seems to have a nicer API and looks more clean. Will try to implement one of them in the next days.

**Comment by alexanderwe** [comment]
@gscriver I decided to use  [Unirest](http://unirest.io/java.html), it wraps nicely around the Apache HttpClient, so I think its the perfect fit here. I will track the implementation of it in https://github.com/alexanderwe/bananaj/issues/12.
