### ISSUE TITLE
Add ability to create campaigns on list groupings (i.e. by segment or conditions)

### ISSUE THREAD

**Issue by gscriver** [alexanderwe/bananaj#18]
Currently you can only specify a list id when creating a campaign. I would like to create campaigns for saved segments in a list.

**Comment by alexanderwe** [comment]
You are right, this is currently not implemented. I will add it, when the base of the library is refactored to the Unirest and @JsonProperty worklfow

**Comment by gscriver** [comment]
Thanks, I need this in a couple of days so I'll go ahead and make an interim implementation.
