### ISSUE TITLE
Please add Mailchimp File Manager support

### ISSUE THREAD

**Issue by gscriver** [alexanderwe/bananaj#24]
Please implement the Mailchimp File Manager API.

**Comment by alexanderwe** [comment]
I will try to update the library as soon as possible. Had a lot to do in the past months, therefore I was unable to maintain the repo that much. I will merge the outstanding pull requests as soon as possible and also try to update the library.

**Comment by gscriver** [comment]
I just discovered the file manager has already been implemented. The manager class is located in a model package (com.github.alexanderwe.bananaj.model.filemanager), not where I expected to find it. 

I am closing this issue because File Manager has already been implemented.

**Comment by alexanderwe** [comment]
Okay, I thought you were meaning I should implemented the updated version of the file manager API. Sorry for the misunderstanding. But still I try to update the lib as soon as possible.

**Comment by gscriver** [comment]
I'll create a new ticket to update the file manager API. I have only made a cursory look at it but have noticed a couple of things. There is no pagination. I have thousands of files so pagination is a must. There is also no convenience accessor method in the main MailChimpConnection class, which is why I didn't think it had been implemented.

I'm planning on updating bananaj to support my specific needs and will create tickets and pull requests as I do so.

**Comment by alexanderwe** [comment]
Thanks a lot for your ongoing support and feature additions. As I mentioned in #12 I think about postponing and maybe drop the idea of using Jackson databdinings for this library. I think what you did is very good and we need some flexibility in handling JSON responses which can sometimes be tricky with bindings in my opinion.
