### ISSUE TITLE
Error adding Unicode content to a campaign

### ISSUE THREAD

**Issue by gscriver** [alexanderwe/bananaj#27]
MailChimp API returns error status 400 when content contains Unicode.
URL: PUT https://us6.api.mailchimp.com/3.0/campaigns/[id]/content 
Reason: Bad Request - JSON Parse Error 
Details: We encountered an unspecified JSON parsing error.

**Comment by gscriver** [comment]
I have identified the cause to be improper UTF-8 encoding of the request body. This affects the PUT/POST/PATCH transport methods.

I am testing a fix for this issue and will create a pull request shortly.

**Comment by alexanderwe** [comment]
Ah alright 👍 , was also going to work on this right now. I will let you do the fix and will also take a look at it. I will then merge the fix into the `develop` branch since I changed some code in the `Connection` class, and did some minor changes to the code there.

**Comment by alexanderwe** [comment]
Is resolved by merge #28 on `develop`. Thanks for your continuous work !
