### ISSUE TITLE
Refactor bananaj into a parent package

### ISSUE THREAD

**Issue by gscriver** [alexanderwe/bananaj#7]
Please refactor the library into a package namespace consistent with Java package naming conventions. E.g. com.domain.bananaj or at least 'bananaj.connection, bananaj.model, and bananaj.utils.

**Comment by alexanderwe** [comment]
You are right, definitely need to resolve this. At the time of writing the library I completely forgot it. 
Currently I do not find time enough time to maintain the library in a complete manner. I will try to change it on the weekend.

**Comment by gscriver** [comment]
I have some time over the next few weeks and will contribute what I can.

**Comment by alexanderwe** [comment]
I updated the master branch to the  new package naming convention. Additionally I also adapted the "Git Flow" pattern for this repo.
@gscriver Thank you a lot for this issue. Definitely need to revise this package and update it more frequent. Any help is much appreciated 👍
